services:
  # 1. Base de Datos
  mysqldb:
    image: mysql:8.0
    container_name: muebleria_db
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASSWORD}
      MYSQL_DATABASE: ${DB_NAME}
    ports:
      - "${MYSQL_LOCAL_PORT}:3306"
    networks:
      - red-muebleria
    healthcheck:
      test: ["CMD", "mysqladmin" ,"ping", "-h", "localhost", "-u", "root", "-p${DB_ROOT_PASSWORD}"]
      timeout: 20s
      retries: 10

  # 2. Backend
  backend:
    build: ./backend
    container_name: muebleria_backend
    ports:
      - "${BACKEND_LOCAL_PORT}:8080"
    environment:
      - MYSQL_URL=jdbc:mysql://${DB_HOST}:${DB_PORT}/${DB_NAME}?allowPublicKeyRetrieval=true&useSSL=false
      - MYSQL_USER=root
      - MYSQL_PASS=${DB_ROOT_PASSWORD}
    depends_on:
      mysqldb:
        condition: service_healthy
    networks:
      - red-muebleria

  # 3. Frontend
  frontend:
    build: ./frontend
    container_name: muebleria_frontend
    ports:
      - "${FRONTEND_LOCAL_PORT}:80"
    depends_on:
      - backend
    networks:
      - red-muebleria

networks:
  red-muebleria:
    driver: bridge