version: '3.8'

services:
  # 1. Base de Datos
  mysqldb:
    image: mysql:8.0
    container_name: muebleria_db
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_PASS}
      MYSQL_DATABASE: muebleria_db
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASS}
    ports:
      - "3307:3306" 
    networks:
      - red-muebleria
    healthcheck:
      test: ["CMD", "mysqladmin" ,"ping", "-h", "localhost"]
      timeout: 20s
      retries: 10

  # 2. Backend
  backend:
    build: ./backend
    container_name: muebleria_backend
    ports:
      - "8080:8080"
    environment:
      - MYSQL_URL=jdbc:mysql://mysqldb:3306/muebleria_db?allowPublicKeyRetrieval=true&useSSL=false
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_PASS=${MYSQL_PASS}
    depends_on:
      mysqldb:
        condition: service_healthy
    networks:
      - red-muebleria

  # 3. Frontend
  frontend:
    build: ./frontend
    container_name: muebleria_frontend
    ports:
      - "3000:80" 
    depends_on:
      - backend
    networks:
      - red-muebleria

networks:
  red-muebleria:
    driver: bridge